#!/usr/bin/python3
from os import system, remove, listdir
from os.path import isfile, join
from sys import argv
from time import sleep


def migrate():
    system("./manage.py makemigrations mvp")
    sleep(0.4)
    # system("./manage.py makemigrations")
    # sleep(0.4)
    system("./manage.py migrate")
    sleep(0.4)


def launch():
    migrate()
    system("./manage.py runserver")


def clean_directory(path):
    file = [f for f in listdir(path) if isfile(join(path, f))]
    for f in file:
        print("Removing file: %s" % f)
        remove(join(path, f))
    system("./manage.py makemigrations")
    sleep(0.4)


def clean_directories():
    paths = [
        "mvp/migrations",
        ]
    for path in paths:
        clean_directory(path)


if __name__ == '__main__':
    if "clean" in argv:
        clean_directories()
    launch()
