# Generated by Django 2.2.7 on 2019-11-28 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='le nom du client.', max_length=150, verbose_name='le nom du client.')),
                ('email', models.EmailField(default=None, help_text="l'email du client", max_length=150, verbose_name='email du client')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'client',
                'ordering': ['company__id', 'commercial__id', 'account_manager__id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commercials',
                'ordering': ['company__id', 'user', 'user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="préciser le nom de l'entreprise.", max_length=150, verbose_name="nom de l'entreprise.")),
                ('ceo', models.OneToOneField(help_text="préciser le CEO de l'entreprise.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="CEO de l'entreprise.")),
            ],
            options={
                'verbose_name': 'entreprise',
                'verbose_name_plural': 'entreprises',
                'ordering': ['ceo__id'],
            },
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='description du conseil', max_length=300, verbose_name="conseil's description")),
                ('price', models.PositiveIntegerField(default=0, help_text='montant total du conseil (EN EUROS)', verbose_name='montant total du conseil.')),
                ('payed', models.BooleanField(default=False, help_text='précisez si le conseil est déjà payé.', verbose_name='si le conseil est payé.')),
            ],
            options={
                'verbose_name': 'conseil',
                'verbose_name_plural': 'conseils',
                'ordering': ['contract__id', 'payed', 'price', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='description du contrat', max_length=100, verbose_name='description du contrat')),
                ('price', models.PositiveIntegerField(default=0, help_text='montant total du contrat (EN EUROS)', verbose_name='montant total du contrat.')),
                ('payed', models.BooleanField(default=False, help_text='précisez si le contrat est payé en intégralité.', verbose_name='si le contrat est payé en intégralité.')),
                ('validated', models.BooleanField(default=False, help_text='précisez si le contract est validé..', verbose_name='si le contract est validé.')),
                ('client', models.ForeignKey(default=None, help_text='client cible du contrat', on_delete=django.db.models.deletion.CASCADE, to='mvp.Client', verbose_name='client cible du contrat')),
                ('commercial', models.ForeignKey(default=None, help_text="commercial à l'origine du contrat", on_delete=django.db.models.deletion.CASCADE, to='mvp.Commercial', verbose_name="commercial à l'origine du contrat")),
                ('company', models.ForeignKey(default=None, help_text='entreprise vendeuse du contrat.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name='entreprise vendeuse du contrat.')),
            ],
            options={
                'verbose_name': 'conseil',
                'verbose_name_plural': 'conseils',
                'ordering': ['company__id', 'commercial__id', 'price', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='description du service', max_length=150, verbose_name='description du service')),
                ('price', models.PositiveIntegerField(default=0, help_text='pricing du service (EN EUROS)', verbose_name='pricing du service')),
                ('estimated_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date prévisionelle ???(en mois/jours).', verbose_name='date prévisionelle ???')),
                ('actual_date', models.DateTimeField(default=django.utils.timezone.now, help_text='fin du service (ACTUEL)(en mois/jours).', verbose_name='fin du service (ACTUEL ???)')),
                ('payed', models.BooleanField(default=False, help_text='précisez si le service est déjà payé.', verbose_name='si le service est payé.')),
                ('conseil', models.ForeignKey(default=None, help_text='conseil relatif au service', on_delete=django.db.models.deletion.CASCADE, to='mvp.Conseil', verbose_name='conseil relatif au service')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['payed', 'estimated_date', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Manager General'), (3, 'Factu Manager'), (2, 'Account Manager')], default=3, help_text='préciser son rôle.', verbose_name='rôle du manager.')),
                ('company', models.ForeignKey(default=None, help_text="préciser l'entreprise de ce manager.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name='entreprise du manager.')),
                ('user', models.OneToOneField(help_text="préciser l'utilisateur lié à ce manager.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="l'utilisateur lié à ce manager")),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
                'ordering': ['company__id', 'role', 'user', 'user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='description de la license', max_length=150, verbose_name='description de la license.')),
                ('price', models.PositiveIntegerField(default=0, help_text='coût de la license (EN EUROS)', verbose_name='coût de la license')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='date de début (en mois/jours).', verbose_name='date de début')),
                ('duration', models.DurationField(default='21 days', help_text='durée de la license (en mois/jours).', verbose_name='durée de la license')),
                ('payed', models.BooleanField(default=False, help_text='précisez si le service est déjà payé.', verbose_name='si le service est payé.')),
                ('contract', models.ForeignKey(default=None, help_text='préciser le contrat dans lequel est inclus ce conseil.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Contract', verbose_name='le contrat dans lequel est inclus ce conseil.')),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
                'ordering': ['contract__id', 'price', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='description de la facture', max_length=300, verbose_name="invoice's description")),
                ('price', models.PositiveIntegerField(default=0, help_text='montant total de la facture (EN EUROS).', verbose_name='montant total de la facture.')),
                ('payed', models.BooleanField(default=False, help_text='précisez si la facture est payée', verbose_name='si la facture est payée.')),
                ('company', models.ForeignKey(help_text="préciser l'entreprise de cette facture.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="l'entreprise de cette facture.")),
                ('conseil', models.ForeignKey(blank=True, default=None, help_text='préciser le ou les conseil(s) à facturer.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Conseil', verbose_name='le ou les conseil(s) relatif(s) à cette facture.')),
                ('contract', models.ForeignKey(blank=True, default=None, help_text='préciser le ou les conseil(s) à facturer.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Contract', verbose_name='le ou les conseil(s) relatif(s) à cette facture.')),
                ('license', models.ForeignKey(blank=True, default=None, help_text='préciser le ou les conseil(s) à facturer.', on_delete=django.db.models.deletion.CASCADE, to='mvp.License', verbose_name='le ou les conseil(s) relatif(s) à cette facture.')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['company__id', 'payed', 'price', 'description'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='factu_manager',
            field=models.ForeignKey(default=None, help_text='préciserle responsable de la facturation de ce contrat.', on_delete=django.db.models.deletion.CASCADE, related_name='factu_manager', to='mvp.Manager', verbose_name='le responsable de la facturation de ce contrat.'),
        ),
        migrations.AddField(
            model_name='conseil',
            name='contract',
            field=models.ForeignKey(default=None, help_text='préciser le contrat dans lequel est inclus ce conseil.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Contract', verbose_name='le contrat dans lequel est inclus ce conseil.'),
        ),
        migrations.AddField(
            model_name='commercial',
            name='company',
            field=models.ForeignKey(default=None, help_text="préciser l'entreprise de ce commercial.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="l'entreprise de ce commercial."),
        ),
        migrations.AddField(
            model_name='commercial',
            name='user',
            field=models.OneToOneField(default=None, help_text="préciser l'utilisateur lié à ce commercial.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="l'utilisateur lié à ce commercial."),
        ),
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(default=None, help_text='préciserle responsable clientièle de ce client.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Manager', verbose_name='le responsable clientièle de ce client.'),
        ),
        migrations.AddField(
            model_name='client',
            name='commercial',
            field=models.ForeignKey(default=None, help_text='préciser le commercial relatif à ce client.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Commercial', verbose_name='le commercial ayant ramené le client.'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=None, help_text="préciser l'entreprise du client.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="l'entreprise du client."),
        ),
    ]
