# Generated by Django 2.2.7 on 2019-11-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company', 'commercial__id', 'name'], 'verbose_name': 'client', 'verbose_name_plural': 'client'},
        ),
    ]
