# Generated by Django 2.2.7 on 2019-12-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(0, 'Pas encore effectué'), (2, 'Ne sera jamais effectué'), (1, 'Effectué')], default=0, help_text='précisez si le service est effectué.', verbose_name='si le service est effectué.'),
        ),
    ]
