# Generated by Django 2.2.7 on 2019-12-05 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 19, 43, 58, 163181, tzinfo=utc), help_text='date de fin du conseil.', verbose_name='date de fin du conseil'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 19, 43, 58, 160962, tzinfo=utc), help_text='date de fin du contrat.', verbose_name='date de fin du contrat'),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 19, 43, 58, 165009, tzinfo=utc), help_text='durée de la license (en mois/jours).', verbose_name='durée de la license'),
        ),
    ]
