# Generated by Django 2.2.7 on 2019-12-05 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_auto_20191205_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseil',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 20, 10, 25, 932544, tzinfo=utc), help_text='date de fin du conseil.', verbose_name='date de fin du conseil'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 20, 10, 25, 931003, tzinfo=utc), help_text='date de fin du contrat.', verbose_name='date de fin du contrat'),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 5, 20, 10, 25, 933855, tzinfo=utc), help_text='durée de la license (en mois/jours).', verbose_name='durée de la license'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager General'), (2, 'Account Manager'), (3, 'Factu Manager')], default=3, help_text='préciser son rôle.', verbose_name='rôle du manager.'),
        ),
    ]
