# Generated by Django 2.2.7 on 2019-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_auto_20191128_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='payed',
            field=models.BooleanField(default=False, help_text='précisez si la license est déjà payée.', verbose_name='si la license est payée.'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account Manager'), (1, 'Manager General'), (3, 'Factu Manager')], default=3, help_text='préciser son rôle.', verbose_name='rôle du manager.'),
        ),
    ]
