# Generated by Django 2.2.7 on 2019-11-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_auto_20191120_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=300, verbose_name="service's description"),
        ),
    ]
