# Generated by Django 2.2.7 on 2019-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_auto_20191129_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account Manager'), (3, 'Factu Manager'), (1, 'Manager General')], default=3, help_text='préciser son rôle.', verbose_name='rôle du manager.'),
        ),
    ]
