# Generated by Django 2.2.7 on 2019-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_auto_20191211_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(2, 'Ne sera jamais effectué'), (1, 'Effectué'), (0, 'Pas encore effectué')], default=0, help_text='précisez si le service est effectué.', verbose_name='si le service est effectué.'),
        ),
    ]
