# Generated by Django 2.2.7 on 2019-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_auto_20191120_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(help_text='description de la license', max_length=300, verbose_name="license's description"),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='description du service', max_length=300, verbose_name="service's description"),
        ),
    ]
