# Generated by Django 2.2.7 on 2019-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_auto_20191120_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (3, 'Factu Manager'), (2, 'Account Manager')], default=None, verbose_name="manager's type"),
        ),
    ]
