# Generated by Django 2.2.7 on 2019-11-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_auto_20191106_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user_id'], 'verbose_name': 'profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'STAFF'), (1, 'DEV'), (3, 'CEO'), (4, 'Commercial')], default=4, unique=True, verbose_name='user type'),
        ),
    ]
