# Generated by Django 2.2.7 on 2019-11-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_auto_20191120_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Account Manager'), (3, 'Factu Manager')], default=None, verbose_name="manager's type"),
        ),
    ]
