# Generated by Django 2.2.7 on 2019-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0008_auto_20191120_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['company__id', 'user'], 'verbose_name': 'manager', 'verbose_name_plural': 'managers'},
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account'), (3, 'Factu'), (1, 'Manager')], default=None, verbose_name="manager's type"),
        ),
    ]
