# Generated by Django 2.2.7 on 2019-11-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvp', '0008_auto_20191106_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='ceo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name="company's ceo"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Commercial'), (1, 'DEV'), (2, 'STAFF'), (3, 'CEO')], default=4, unique=True, verbose_name='user type'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='client', max_length=50, verbose_name='client name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', related_query_name='clients', to='mvp.Companies')),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ['company'],
            },
        ),
    ]
