# Generated by Django 2.2.7 on 2019-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0009_auto_20191120_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (3, 'Factu'), (2, 'Account')], default=None, verbose_name="manager's type"),
        ),
    ]
