# Generated by Django 2.2.7 on 2019-11-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0012_auto_20191120_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['company__id', 'commercial__id', 'cost', 'description'], 'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['company__id', 'commercial__id', 'pricing', 'description'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Account'), (3, 'Factu')], default=None, verbose_name="manager's type"),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='description de la license', max_length=300, verbose_name="license's description")),
                ('pricing', models.PositiveIntegerField(default=0, help_text='pricing du service (EN EUROS)', verbose_name='pricing de la facture')),
                ('client', models.ForeignKey(help_text='le client relatif à cette facture', on_delete=django.db.models.deletion.CASCADE, to='mvp.Client', verbose_name="invoice's client")),
                ('commercial', models.ForeignKey(help_text='le commercial relatif à cette facture', on_delete=django.db.models.deletion.CASCADE, to='mvp.Commercial', verbose_name="invoice's commercial")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="company's invoices+", related_query_name="company's invoices", to='mvp.Company')),
                ('licenses', models.ManyToManyField(help_text='le commercial relatif à cette facture', to='mvp.License', verbose_name="invoice's commercial")),
                ('services', models.ManyToManyField(help_text='le commercial relatif à cette facture', to='mvp.Service', verbose_name="invoice's commercial")),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['company__id', 'commercial__id', 'pricing', 'description'],
            },
        ),
    ]
