# Generated by Django 2.2.7 on 2019-11-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0014_auto_20191106_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Commercial'), (3, 'CEO'), (2, 'STAFF'), (1, 'DEV')], default=4, unique=True, verbose_name='user type'),
        ),
    ]
