# Generated by Django 2.2.7 on 2019-11-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0014_auto_20191121_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company__id', 'commercial__id', 'name'], 'verbose_name': 'client', 'verbose_name_plural': 'client'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(help_text="Indicate invoice's company", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="invoice's company"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(help_text='description de la facture', max_length=300, verbose_name="invoice's description"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='licenses',
            field=models.ManyToManyField(help_text='les licenses relatif à cette facture', to='mvp.License', verbose_name="invoice's licenses"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(help_text='les services relatifs à cette facture', to='mvp.Service', verbose_name="invoice's services"),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account'), (1, 'Manager'), (3, 'Factu')], default=None, verbose_name="manager's type"),
        ),
    ]
