# Generated by Django 2.2.7 on 2019-11-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0015_auto_20191121_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (3, 'Factu'), (2, 'Account')], default=None, verbose_name="manager's type"),
        ),
    ]
