# Generated by Django 2.2.7 on 2019-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0016_auto_20191121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account'), (3, 'Factu'), (1, 'Manager')], default=None, verbose_name="manager's type"),
        ),
    ]
