# Generated by Django 2.2.7 on 2019-12-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0018_auto_20191214_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager General'), (3, 'Factu Manager'), (2, 'Account Manager')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(2, 'Ne sera jamais effectué'), (1, 'Effectué'), (0, 'Pas encore effectué')], default=0, help_text='précisez si le service est effectué.', verbose_name='si le service est effectué.'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, help_text="l'email du client", max_length=150, verbose_name='email du ')),
                ('role', models.PositiveSmallIntegerField(choices=[(3, 'Responsable Facturation'), (2, 'Responsable Clientèle'), (1, 'Manager'), (4, 'Commercial')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.')),
                ('company', models.ForeignKey(help_text="préciser l'entreprise de cette invitation.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="l'entreprise de cette invitation.")),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['company__id', 'role'],
            },
        ),
    ]
