# Generated by Django 2.2.7 on 2019-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0020_auto_20191106_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DEV'), (3, 'CEO'), (4, 'Commercial'), (2, 'STAFF')], default=4, unique=True, verbose_name='user type'),
        ),
    ]
