# Generated by Django 2.2.7 on 2019-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0020_auto_20191123_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Factu'), (2, 'Account'), (1, 'Manager')], default=None, verbose_name="manager's type"),
        ),
    ]
