# Generated by Django 2.2.7 on 2019-12-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0021_auto_20191215_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Commercial'), (2, 'Responsable Clientèle'), (3, 'Responsable Facturation'), (1, 'Manager')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Factu Manager'), (2, 'Account Manager'), (1, 'Manager General')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(0, 'Pas encore effectué'), (2, 'Ne sera jamais effectué'), (1, 'Effectué')], default=0, help_text='précisez si le service est effectué.', verbose_name='si le service est effectué.'),
        ),
    ]
