# Generated by Django 2.2.7 on 2019-11-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0021_auto_20191123_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (2, 'Account'), (3, 'Factu')], default=None, verbose_name="manager's type"),
        ),
    ]
