# Generated by Django 2.2.7 on 2019-12-16 13:15

import django.utils.timezone
from django.db import migrations, models

import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0022_auto_20191215_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='company',
            field=models.ForeignKey(help_text="Préciser l'entreprise de cette invitation.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="L'entreprise de cette invitation."),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(default=None, help_text="L'email du destinataire.", max_length=150, verbose_name='Email du destinataire.'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Responsable Clientèle'), (4, 'Commercial'), (1, 'Manager'), (3, 'Responsable Facturation')], default=4, help_text='Préciser le rôle de la personne', verbose_name='Rôle de la personne'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(help_text="Préciser l'entreprise de cette facture.", on_delete=django.db.models.deletion.CASCADE, to='mvp.Company', verbose_name="L'entreprise de cette facture."),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='conseils',
            field=models.ManyToManyField(default=None, help_text='Préciser le ou les conseil(s) à facturer.', to='mvp.Conseil', verbose_name='Le ou les conseil(s) relatif(s) à cette facture.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(default=None, help_text='Préciser le contrat relatif à cette facture.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Contract', verbose_name='Le contrat relatif à cette facture.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de la facture.', verbose_name='Date de la facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(help_text='Description de la facture', max_length=300, verbose_name="Invoice's description"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='facturated',
            field=models.BooleanField(default=False, help_text='Précisez si la facture est facturée', verbose_name='Si la facture est facturée.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='licenses',
            field=models.ManyToManyField(default=None, help_text='Préciser le ou les licenses(s) à facturer.', to='mvp.License', verbose_name='Le ou les licenses(s) relatif(s) à cette facture.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payed',
            field=models.BooleanField(default=False, help_text='Précisez si la facture est payée', verbose_name='Si la facture est payée.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Montant total de la facture (EN EUROS).', verbose_name='Montant total de la facture.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='contract',
            field=models.ForeignKey(default=None, help_text='Préciser le contrat dans lequel est inclus cette licence.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Contract', verbose_name='Le contrat dans lequel est inclus cette licence.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.CharField(help_text='Description de la license.', max_length=150, verbose_name='Description de la license.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Précisez la durée totale de la licence (en mois).', verbose_name='Durée totale de la licence.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de fin de la licence.', verbose_name='Date de fin de la licence.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='payed',
            field=models.BooleanField(default=False, help_text='Précisez si la licence est déjà payée.', verbose_name='Si la licence est payée.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Coût de la licence (€).', verbose_name='Coût de la licence'),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de début de la licence.', verbose_name='Date de début de la licence.'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager General'), (3, 'Factu Manager'), (2, 'Account Manager')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='actual_date',
            field=models.DateField(default=None, help_text='Fin du service', null=True, verbose_name='Fin du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='conseil',
            field=models.ForeignKey(default=None, help_text='Conseil relatif au service', on_delete=django.db.models.deletion.CASCADE, to='mvp.Conseil', verbose_name='Conseil relatif au service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(help_text='Description du service', max_length=150, verbose_name='Description du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(1, 'Effectué'), (0, 'Pas encore effectué'), (2, 'Ne sera jamais effectué')], default=0, help_text='Précisez si le service est effectué.', verbose_name='Si le service est effectué.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Sélectionnez une date prévisionelle.', verbose_name='Date prévisionelle'),
        ),
        migrations.AlterField(
            model_name='service',
            name='junior_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Précisez le Jour homme junior nécessaire pour ce service.', max_digits=5, verbose_name='Jour-hommes junior nécessaire pour ce service.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payed',
            field=models.BooleanField(default=False, help_text='Précisez si le service est déjà payé.', verbose_name='Si le service est payé.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Pricing du service (€)', verbose_name='Pricing du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='senior_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Précisez le Jour homme senior nécessaire pour ce service.', max_digits=5, verbose_name='Jour-hommes senior nécessaire pour ce service.'),
        ),
    ]
