# Generated by Django 2.2.7 on 2019-11-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0023_auto_20191106_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'CEO'), (2, 'STAFF'), (1, 'DEV'), (4, 'Commercial')], default=4, unique=True, verbose_name='user type'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='client', max_length=50, verbose_name='client name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', related_query_name='clients', to='mvp.Companies')),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ['company'],
            },
        ),
    ]
