# Generated by Django 2.2.7 on 2019-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0024_auto_20191216_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager General'), (3, 'Factu Manager'), (2, 'Account Manager')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(1, 'Effectué'), (2, 'Ne sera jamais effectué'), (0, 'Pas encore effectué')], default=0, help_text='Précisez si le service est effectué.', verbose_name='Si le service est effectué.'),
        ),
    ]
