# Generated by Django 2.2.7 on 2019-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0024_auto_20191106_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DEV'), (2, 'STAFF'), (4, 'Commercial'), (3, 'CEO')], default=4, unique=True, verbose_name='user type'),
        ),
    ]
