# Generated by Django 2.2.7 on 2019-11-06 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0025_auto_20191106_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'STAFF'), (1, 'DEV'), (4, 'Commercial'), (3, 'CEO')], default=4, unique=True, verbose_name='user type'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='')),
                ('cost', models.PositiveIntegerField(default=0, help_text='coût de la license (EN EUROS)', verbose_name='coût de la license')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, help_text='date de début (en mois/jours).', verbose_name='date de début')),
                ('duration', models.DurationField(help_text='durée de la license (en mois/jours).', verbose_name='durée de la license')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name="company's licenses+", related_query_name="company's licenses", to='mvp.Companies')),
            ],
            options={
                'verbose_name': 'License',
                'ordering': ['cost'],
            },
        ),
    ]
