# Generated by Django 2.2.7 on 2019-12-17 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0025_auto_20191216_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.OneToOneField(help_text="Préciser le CEO de l'entreprise.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="CEO de l'entreprise."),
        ),
        migrations.AlterField(
            model_name='company',
            name='invoice_nb',
            field=models.PositiveIntegerField(default=1, help_text="Numéro de factures de l'entreprise.", verbose_name="Numéro de factures de l'entreprise."),
        ),
        migrations.AlterField(
            model_name='company',
            name='junior_day',
            field=models.PositiveIntegerField(default=0, help_text='Précisez le prix du jour homme junior de cette entreprise.', verbose_name='Prix du Jour homme junior de cette entreprise.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text="Préciser le nom de l'entreprise.", max_length=150, verbose_name="Nom de l'entreprise."),
        ),
        migrations.AlterField(
            model_name='company',
            name='senior_day',
            field=models.PositiveIntegerField(default=0, help_text='Précisez le prix du jour homme senior de cette entreprise.', verbose_name='Prix du Jour homme senior de cette entreprise.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(default=None, help_text="Numéro SIRET de l'entreprise.", max_length=14, verbose_name="Numéro SIRET de l'entreprise."),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='contract',
            field=models.ForeignKey(default=None, help_text='Préciser le contrat dans lequel est inclus ce conseil.', on_delete=django.db.models.deletion.CASCADE, to='mvp.Contract', verbose_name='Le contrat dans lequel est inclus ce conseil.'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='description',
            field=models.CharField(help_text='Description du conseil', max_length=150, verbose_name='Description du conseil.'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Précisez la durée totale du conseil (en mois).', verbose_name='Durée totale (en mois).'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='end_date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de fin du conseil.', verbose_name='Date de fin du conseil.'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='payed',
            field=models.BooleanField(default=False, help_text='Précisez si le conseil est déjà payé.', verbose_name='Si le conseil est payé.'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Montant total (€)', verbose_name='Montant total.'),
        ),
        migrations.AlterField(
            model_name='conseil',
            name='start_date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de début du conseil.', verbose_name='Date de début.'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Manager'), (4, 'Commercial'), (3, 'Responsable Facturation'), (2, 'Responsable Clientèle')], default=4, help_text='Préciser le rôle de la personne', verbose_name='Rôle de la personne'),
        ),
        migrations.AlterField(
            model_name='license',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Précisez la durée totale (en mois).', verbose_name='Durée totale (en mois).'),
        ),
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de fin.', verbose_name='Date de fin.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Montant (€).', verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(default=mvp.models.GetDate, help_text='Date de début.', verbose_name='Date de début.'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account Manager'), (3, 'Factu Manager'), (1, 'Manager General')], default=3, help_text='préciser le rôle du manager.', verbose_name='rôle du manager.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(0, 'Pas encore effectué'), (1, 'Effectué'), (2, 'Ne sera jamais effectué')], default=0, help_text='Précisez si le service est effectué.', verbose_name='Si le service est effectué.'),
        ),
    ]
