# Generated by Django 2.2.7 on 2019-11-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0028_auto_20191123_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Account'), (1, 'Manager'), (3, 'Factu')], default=None, verbose_name="manager's type"),
        ),
    ]
