# Generated by Django 2.2.7 on 2019-11-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0028_auto_20191106_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Commercial'), (1, 'DEV'), (3, 'CEO'), (2, 'STAFF')], default=4, unique=True, verbose_name='user type'),
        ),
    ]
