# Generated by Django 2.2.7 on 2019-11-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0029_auto_20191106_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'STAFF'), (4, 'Commercial'), (3, 'CEO'), (1, 'DEV')], default=4, unique=True, verbose_name='user type'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('cost', models.PositiveIntegerField(default=0, help_text='coût du service (EN EUROS)', verbose_name='coût du service')),
                ('estimated_date', models.DateTimeField(help_text='date prévisionelle ???(en mois/jours).', verbose_name='date prévisionelle ???')),
                ('actual_date', models.DateTimeField(help_text='fin du Service (ACTUEL)(en mois/jours).', verbose_name='fin du Service (ACTUEL ???)')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name="company's services+", related_query_name="company's services", to='mvp.Companies')),
            ],
            options={
                'verbose_name': 'service',
                'ordering': ['cost'],
            },
        ),
    ]
