# Generated by Django 2.2.7 on 2019-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0033_auto_20191124_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Factu'), (1, 'Manager'), (2, 'Account')], default=None, verbose_name="manager's type"),
        ),
    ]
