# Generated by Django 2.2.7 on 2019-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0035_auto_20191106_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['pricing'], 'verbose_name': 'service'},
        ),
        migrations.RenameField(
            model_name='license',
            old_name='description',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
        migrations.AddField(
            model_name='service',
            name='pricing',
            field=models.PositiveIntegerField(default=0, help_text='pricing du service (EN EUROS)', verbose_name='pricing du service'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=70, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'STAFF'), (1, 'DEV'), (3, 'CEO'), (4, 'Commercial')], default=4, verbose_name='user type'),
        ),
    ]
