# Generated by Django 2.2.7 on 2019-12-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0036_auto_20191219_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facturation_delay',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 Jours'), (15, '15 Jours'), (90, '90 Jours'), (60, '60 Jours'), (45, '45 Jours'), (75, '75 Jours')], default=45, help_text='Précisez le délai à partir duquel un client est considéré en retard de paiement.', verbose_name='Délai de facturation.'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Responsable Clientèle'), (4, 'Commercial'), (1, 'Manager'), (3, 'Responsable Facturation')], default=4, help_text='Préciser le rôle de la personne', verbose_name='Rôle de la personne'),
        ),
    ]
