# Generated by Django 2.2.7 on 2019-12-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0037_auto_20191219_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facturation_delay',
            field=models.PositiveSmallIntegerField(choices=[(90, '90 Jours'), (30, '30 Jours'), (15, '15 Jours'), (75, '75 Jours'), (60, '60 Jours'), (45, '45 Jours')], default=45, help_text='Précisez le délai à partir duquel un client est considéré en retard de paiement.', verbose_name='Délai de facturation.'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Responsable Facturation'), (4, 'Commercial'), (2, 'Responsable Clientèle'), (1, 'Manager')], default=4, help_text='Préciser le rôle de la personne', verbose_name='Rôle de la personne'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(2, 'Ne sera jamais effectué'), (0, 'Pas encore effectué'), (1, 'Effectué')], default=0, help_text='Précisez si le service est effectué.', verbose_name='Si le service est effectué.'),
        ),
    ]
