# Generated by Django 2.2.7 on 2019-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0037_auto_20191106_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='subject',
            field=models.CharField(help_text='sujet de la license', max_length=300, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Commercial'), (2, 'STAFF'), (3, 'CEO'), (1, 'DEV')], default=4, verbose_name='user type'),
        ),
    ]
