# Generated by Django 2.2.7 on 2019-12-21 20:04

from django.db import migrations, models

import mvp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0041_auto_20191221_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='facturated',
        ),
        migrations.AddField(
            model_name='invoice',
            name='facturated_date',
            field=models.DateField(default=None, help_text='Précisez la date de facturation', null=True, verbose_name='Date de facturation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(default=None, help_text='PDF de la facture.', null=True, upload_to=mvp.models.getInvoiceStorage, verbose_name='PDF de la facture.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='facturation_delay',
            field=models.PositiveSmallIntegerField(choices=[(75, '75 Jours'), (15, '15 Jours'), (45, '45 Jours'), (90, '90 Jours'), (60, '60 Jours'), (30, '30 Jours')], default=45, help_text='Précisez le délai à partir duquel un client est considéré en retard de paiement.', verbose_name='Délai de facturation.'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Responsable Facturation'), (2, 'Responsable Clientèle'), (4, 'Commercial'), (1, 'Manager')], default=4, help_text='Préciser le rôle de la personne', verbose_name='Rôle de la personne'),
        ),
        migrations.AlterField(
            model_name='service',
            name='done',
            field=models.SmallIntegerField(choices=[(2, 'Ne sera jamais effectué'), (1, 'Effectué'), (0, 'Pas encore effectué')], default=0, help_text='Précisez si le service est effectué.', verbose_name='Si le service est effectué.'),
        ),
    ]
